name: cache
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-cache
  cancel-in-progress: true
jobs:
  clean:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mokmok-dev/delete-actions-cache@v0.1.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
